# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgRHYKMll277NhubQcDlXFnWNLBRcQp_
"""

import requests

def check_website(url):
    try:
        response = requests.get(url)
        return f"Website {url} is up (status: {response.status_code})."
    except requests.exceptions.RequestException:
        return f"Website {url} is unreachable."

# Test the function
print(check_website("https://uok.ac.rw"))